# Generated by Django 5.2.4 on 2025-07-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myQuill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
